name: testversion1
description: "A new Flutter project."
publish_to: 'none'  # 공개하지 않을 경우 'none'으로 유지

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependency_overrides:
  win32: ^3.1.4

dependencies:
  flutter:
    sdk: flutter
  dart_openai: ^1.3.0
  http: ^0.13.4
  shared_preferences: ^2.5.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  firebase_core: ^2.20.0
  firebase_analytics: ^10.2.0
  firebase_crashlytics: ^3.0.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.0.16
  google_ml_kit: ^0.19.0  # 사용 가능한 최신 버전을 확인하세요.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
